spring.application.name=PaymentService

# Actuator
management.endpoints.web.exposure.include=health,info,prometheus

# Metrics
management.prometheus.metrics.export.enabled=true

# Tracing
management.tracing.enabled=true
management.tracing.sampling.probability=0.1
management.otlp.tracing.endpoint=http://tempo:4317

management.endpoint.health.probes.enabled=true